const haikuThemes = [
  "Spring Dawn",
  "Summer Noon",
  "Autumn Dusk",
  "Winter Midnight",
  "Cherry Blossom",
  "Plumb blossom",
  "Maple Leaves",
  "Mountain Mist",
  "River Stones",
  "Moon Reflection",
  "Sunset Glow",
  "Raindrop Melody",
  "Snowflake Lace",
  "Pine Whisper",
  "Bamboo Shade",
  "Lotus Bloom",
  "Orchid Grace",
  "Willow Sway",
  "Pebble Path",
  "Cloud Shadows",
  "Star Trail",
  "Ocean Breeze",
  "Sand Dune",
  "Grass Dew",
  "Leaf Rustle",
  "Flower Petal",
  "Birdsong",
  "Frog Chorus",
  "Cricket Hymn",
  "Butterfly Flight",
  "Dragonfly Hover",
  "Firefly Spark",
  "Moss Carpet",
  "Fern Frond",
  "Mushroom Circle",
  "Ivy Vine",
  "Thistle Down",
  "Reed Whistle",
  "Lily Pad",
  "Cattail Fluff",
  "Sunbeam",
  "Moonbeam",
  "Starlight",
  "Fog Veil",
  "Rainbow Arc",
  "Lightning Flash",
  "Thunder Echo",
  "Wind Whisper",
  "Snow Silence",
  "Ice Crystal",
  "Hailstone Drum",
  "River Song",
  "Stream Murmur",
  "Brook Babble",
  "Waterfall Roar",
  "Lake Mirror",
  "Pond Serenity",
  "Sea Horizon",
  "Ocean Depths",
  "Tide Pools",
  "Wave Crests",
  "Coral Gardens",
  "Koi Dance",
  "Heron Stance",
  "Crane beautiful",
  "Swan Elegance",
  "Eagle Flight",
  "Sparrow Flock",
  "Owl Gaze",
  "Hawk Hunt",
  "Falcon Dive",
  "Rabbit Leap",
  "Deer Stroll",
  "Fox Trot",
  "Bear Lumber",
  "Wolf Prowl",
  "Squirrel Scamper",
  "Hedgehog scurry",
  "Turtle Bask",
  "Frog Leap",
  "Insect hidden",
  "Spider Web",
  "Ant March",
  "Bee working",
  "Silkworm Thread",
  "Caterpillar transformation",
  "Butterfly flutter",
  "Moth Flame",
  "Beetle nature",
  "Dragonfly dash",
  "Grasshopper Leap",
  "Cricket Serenade",
  "Firefly Twinkle",
  "Earth Warmth",
  "Fire Glow",
  "Water Flow",
  "Air Dance",
  "Wood Grow",
  "Sun Rise",
  "Moon Phase",
  "Star Gaze",
  "Comet Tail",
  "Aurora Veil",
  "Meteor Shower",
  "Constellation Myth",
  "Galaxy Whirl",
  "Universe Pulse",
  "Time Flow",
  "Season Cycle",
  "Moment Flicker",
  "Memory Echo",
  "Dream Whisper",
  "Hope Spark",
  "Joy Ripple",
  "Sorrow Wave",
  "Peace Calm",
  "Love Radiance",
  "Solitude Depth",
  "Unity Harmony",
  "Wisdom Insight",
  "Creativity Spark",
  "Curiosity Quest",
  "Adventure Leap",
  "Music Melody",
  "Dance Rhythm",
  "Poetry Verse",
  "Story Thread",
  "Myth Legend",
  "Fable Moral",
  "Future Dream",
  "Dawn Over Meadows",
  "Twilight Peaks",
  "Canyon Shadows",
  "Misty Fjords",
  "Rolling Hills at Dusk",
  "Lavender Fields",
  "Sundown on the Prairie",
  "Moonlit Desert",
  "Tidal Estuary",
  "Creekside Willows",
  "Aspen Grove Whispers",
  "Seaside Cliffs",
  "Coral Atoll",
  "Dewy Vineyard",
  "Golden Wheat Field",
  "Frosty Mountain Pass",
  "Sundrenched Valley",
  "Rainforest Canopy",
  "Mangrove Labyrinth",
  "Pine Forest Floor",
  "Meadow Brook Babble",
  "Icy Glacier",
  "Tropical Lagoon",
  "Wind-Swept Dunes",
  "Fiery Volcano Slope",
  "Tranquil Oasis",
  "Glimmering Iceberg",
  "Roaring Waterfalls",
  "Blooming Cactus Desert",
  "Whispering Bamboo Grove",
  "Alpine Meadow",
  "Serpentine River Bend",
  "Majestic Gorge",
  "Radiant Coral Reef",
  "Fog-Enshrouded Hills",
  "Starlit Plateau",
  "Thundering Coastline",
  "Crystalline Lakefront",
  "Flowering Orchard",
  "Rugged Coastline",
  "Sunset on the Marsh",
  "Ancient Petrified Forest",
  "Highland Heather Bloom",
  "Tundra in Bloom",
  "Salt Flat Mirage",
  "Sagebrush Steppe",
  "Sunflower Field at Noon",
  "Moonrise over Wetlands",
  "Stargazer's Mountain Summit",
  "Peony in Full Bloom",
  "Phoenix Feathers Dance",
  "Bamboo in the Wind",
  "Lotus on Still Water",
  "Plum Blossoms in Snow",
  "Ancient Pine under Moon",
  "Koi Fish in the Pond",
  "Jade Dragon Mountains",
  "Silk Road Caravans",
  "Tea Ceremony at Dusk",
  "Chrysanthemum Dew",
  "Dragon Boat Festival",
];

const getRandomHaikuTheme = () =>
  haikuThemes[Math.floor(Math.random() * haikuThemes.length)];

module.exports = { getRandomHaikuTheme };